namespace WitFX.MT4.Server.cls
{
    public enum MessageTypeID : uint
    {
        MT_HeartBeatReqResp_ID = 101,
        MT_LogInRequest_ID = 102,
        MT_LoginResponse_ID = 103,
        MT_MasterAccTransRequest_ID = 104,
        MT_MasterAccTransResponse_ID = 105,
        MT_MasterSettingUpdateRequest_ID = 106,
        MT_MasterSettingUpdateResponse_ID = 107,
        MT_SignalSymSettingTransRequest_ID = 108,
        MT_SignalSymSettingTransResponse_ID = 109,
        MT_SignalNameRequest_ID = 110,
        MT_SignalNameResponse_ID = 111,
        MT_SSPSignalCreateRequest_ID = 112,
        MT_SSPSignalCreateResponse_ID = 113,
        MT_SMSignalCreateRequest_ID = 114,
        MT_SMSignalCreateResponse_ID = 115,
        MT_AddSMFollowerRequest_ID = 116,
        MT_AddSMFollowerResponse_ID = 117,
        MT_AddSSPFollowerRequest_ID = 118,
        MT_AddSSPFollowerResponse_ID = 119,
        MT_CheckPasswordRequest_ID = 120,
        MT_CheckPasswordResponse_ID = 121,
        MT_NewAccountRequest_ID = 122,
        MT_NewAccountResponse_ID = 123,
        MT_MarketDataRequest_ID = 124,
        MT_MarketDataResponse_ID = 125,
        MT_AcknowledgeResponse_ID = 126,
        MT_TradeDisableResponse_ID = 127,
        MT_SocialOrderRequest_ID = 128,
        MT_SocialOrderResponse_ID = 129,
        MT_UserOnlineResponse_ID = 130,
        MT_MT4AccountResponse_ID = 131,
        MT_MyTradeRecordResponse_ID = 132,
        MT_SocialTradeRecordResponse_ID = 133,
        MT_MT4MarginResponse_ID = 134,
        MT_RankingRequest_ID = 135,
        MT_RankingResponse_ID = 136,
        MT_RemoveSMSignalRequest_ID = 137,
        MT_RemoveSMSignalResponse_ID = 138,
        MT_GetSMFollowerRequest_ID = 139,
        MT_GetSMFollowerResponse_ID = 140,
        MT_GetSSPFollowerRequest_ID = 141,
        MT_GetSSPFollowerResponse_ID = 142,
        MT_ChangePasswordRequest_ID = 143,
        MT_ChangePasswordResponse_ID = 144,
        MT_ResetPasswordRequest_ID = 145,
        MT_ResetPasswordResponse_ID = 146,
        MT_GraphRequest_ID = 147,
        MT_ProductRequest_ID = 148,
        MT_ProductResponse_ID = 149,

        MT_GenericFileDataResponse_ID = 201

    }
    public enum FileDataTypeID : uint
    {
        FDMT_MasterUser_ID = 801,
        FDMT_MT4Account_ID = 802,
        FDMT_MT4SymbolInfo_ID = 803,
        FDMT_SignalSymbolSetting_ID = 804,
        FDMT_Signal_ID = 805,
        FDMT_SMSignal_ID = 806,
        FDMT_SSPSignal_ID = 807,
        FDMT_SMFollower_ID = 808,
        FDMT_SSPFollower_ID = 809,
        FDMT_MarketData_ID = 810,
        FDMT_MT4TradeDisableInfo_ID = 811,
        FDMT_MT4Trades_ID = 812,
        FDMT_Ranking_ID = 813,
        FDMT_Graph_ID = 814,
        FDMT_Product_ID = 815
    }
}