; Listing generated by Microsoft (R) Optimizing Compiler Version 19.15.26730.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\jyu43\AppData\Local\Temp\.NETFramework,Version=v4.7.AssemblyAttributes.cpp"
